Screenshot mode is also required for API level 20
Nobody should be running GoIV on Android Wear IMHO, but there are
unexpected crashes on Android 5 with NoClassDefFoundError for the
MediaProjectionManager API, so let's rule that out more clearly.

Related to #315.