Don't initialize Fabric in online debug builds
Currently, when starting online debug builds, I always get on logcat:

```
09-17 11:34:00.381 20381-20446/com.kamron.pogoiv E/Fabric:
Error dealing with settings
java.lang.IllegalArgumentException: Fabric could not be initialized, API
key missing from AndroidManifest.xml. Add the following tag to your
Application element
	<meta-data android:name="io.fabric.ApiKey" android:value="YOUR_API_KEY"/>
```

This initialization currently fails because we provide no API Key for
that case. The Gradle config enables Fabric for online builds but
disables it for debug builds, but maybe this ends up with Fabric
being enabled for online debug builds (it's unclear).